name: doudizhu
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - libcxx=10.0.0
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.7.10
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.12.0
    - astor==0.8.1
    - cached-property==1.5.2
    - cycler==0.10.0
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.37.0
    - h5py==3.2.1
    - importlib-metadata==3.10.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.1
    - numpy==1.20.2
    - opt-einsum==3.3.0
    - pillow==8.2.0
    - protobuf==3.15.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - rlcard==0.2.8
    - six==1.15.0
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.4.1
#prefix: /Users/Josefine/miniconda3/envs/doudizhu
